---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: godofcontainers/node-mongodb
    tag: '6.2.0'

inputs:
  - name: built-project

params:
  CF_API: {{cf-api}}
  CF_USER: {{cf-user}}
  CF_PASSWORD: {{cf-password}}
  CF_ADMIN_USER: {{cf-admin-user}}
  CF_ADMIN_PASSWORD: {{cf-admin-password}}
  CF_ORG: {{cf-org}}
  CF_SPACE: {{cf-space}}
  CF_DOMAIN: {{cf-domain}}
  DB_SERVICE_NAME: {{db-service-name}}
  DB_PLAN_NAME: {{db-plan-name}}
  # Use latest node.js buildpack to enable 5.11.1
  BUILDPACK: https://github.com/cloudfoundry/nodejs-buildpack.git
  # Save file handlers and offload CF stagers
  JOBS: 2

run:
  path: built-project/etc/concourse/scripts/cf-deploy-deploy
