---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: godofcontainers/ubuntu-14.04.4-cf
    tag: 'latest'

inputs:
  - name: built-project

params:
  CF_API: {{cf-api}}
  CF_USER: {{cf-user}}
  CF_PASSWORD: {{cf-password}}
  CF_ADMIN_USER: {{cf-admin-user}}
  CF_ADMIN_PASSWORD: {{cf-admin-password}}
  CF_ORG: {{cf-org}}
  CF_SPACE: {{cf-space}}
  CF_DOMAIN: {{cf-domain}}
  UAA_ADMIN: {{uaa-admin}}
  UAA_SECRET: {{uaa-secret}}
  SYSTEM_CLIENT_ID: {{system-client-id}}
  SYSTEM_CLIENT_SECRET: {{system-client-secret}}
  BRIDGE_CLIENT_ID: {{bridge-client-id}}
  BRIDGE_CLIENT_SECRET: {{bridge-client-secret}}
  CF_CLIENT_ID: {{cf-client-id}}
  CF_CLIENT_SECRET: {{cf-client-secret}}
  CONTAINER_CLIENT_ID: {{container-client-id}}
  CONTAINER_CLIENT_SECRET: {{container-client-secret}}
  OBJECT_STORAGE_CLIENT_ID: {{object-storage-client-id}}
  OBJECT_STORAGE_CLIENT_SECRET: {{object-storage-client-secret}}
  HYSTRIX_CLIENT_ID: {{hystrix-client-id}}
  HYSTRIX_CLIENT_SECRET: {{hystrix-client-secret}}

run:
  path: built-project/etc/concourse/scripts/cf-deploy-infra
