---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: godofcontainers/ubuntu-14.04.4-cf
    tag: 'latest'

inputs:
  - name: abacus

params:
  CF_API: {{cf-api}}
  CF_USER: {{cf-user}}
  CF_PASSWORD: {{cf-password}}
  CF_ADMIN_USER: {{cf-admin-user}}
  CF_ADMIN_PASSWORD: {{cf-admin-password}}
  CF_ORG: {{cf-org}}
  CF_SPACE: {{cf-space}}
  CF_DOMAIN: {{cf-domain}}

run:
  path: abacus/etc/concourse/scripts/cf-test-infra
