---
resources:
  - name: landscape
    type: git
    source:
      uri: {{landscape-git-repo}}
      branch: {{landscape-git-repo-branch}}
      paths: [cf-abacus,abacus-config]
      private_key: {{landscape-git-repo-private-key}}
      skip-ssl-verification: true

jobs:
  - name: abacus-deploy
    plan:
      - aggregate:
        - get: landscape
          trigger: true
      - task: build-abacus
        file: landscape/cf-abacus/etc/concourse/tasks/cf-deploy-build.yml
      - task: setup-abacus-infra
        file: built-project/etc/concourse/tasks/cf-deploy-infra.yml
      - task: deploy-abacus
        file: built-project/etc/concourse/tasks/cf-deploy-deploy.yml
      - task: test-abacus
        file: built-project/etc/concourse/tasks/cf-deploy-test.yml
